(deftheme slate
  "Created 2016-07-31.")

(custom-theme-set-variables
 'slate
 )

(custom-theme-set-faces
 'slate
 '(default ((t (:background "#121416" :foreground "#eaeaea"))))
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#000000" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#000000" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#000000" :inherit font-lock-warning-face :inverse-video t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#424242"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#2a2a2a"))))
 '(border ((((class color) (min-colors 89)) (:background "#424242" :foreground "#424242"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#2a2a2a"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground nil :background "#424242" :weight normal :box (:line-width 1 :color "#969896")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#424242" :weight normal :box (:line-width 1 :color "#424242")))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(region ((((class color) (min-colors 89)) (:background "#424242" :inverse-video nil))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c397d8" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#e7c547"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#e7c547"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background "#424242" :foreground "#d54e53"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e7c547"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#d54e53"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#424242" :foreground "#d54e53"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#c397d8" :foreground "#000000"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#000000"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#424242" :box (:line-width 1 :color "#eaeaea")))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b9ca4a")))))

(provide-theme 'slate)
